spring.application.name=CodeCamp
spring.datasource.url=jdbc:postgresql://172.20.0.2:5432/code_camp
spring.datasource.username=admin
spring.datasource.password=senha_segura_123
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true